name: Convert Yolo Models to OM
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  onnx2om:
    strategy:
      matrix:
        runs-on: [ubuntu-18.04]  # 匹配文档推荐的操作系统
    runs-on: ${{ matrix.runs-on }}
    container:
      image: docker.mirrors.sjtug.sjtu.edu.cn/hispark/qiankunbp:1.0.0  # 官方昇腾开发镜像
      options: --privileged

    steps:
    - name: Download ONNX model
      run: |
        apt-get update && apt install -y wget
        wget --tries=3 https://raw.githubusercontent.com/nhdzlj/model_convert/master/orangeAll.onnx -O bc.onnx

    - name: Convert ONNX to OM with ATC
      shell: bash
      run: |
        source /usr/local/Ascend/ascend-toolkit/script/setenv.sh  # 加载 CANN 环境变量
        atc --model=bc.onnx --framework=5 --output=./om/yolo --soc_version=Hi3519DV500 --input_shape="images:1,3,640,640"

    - name: Upload OM artifact
      uses: actions/upload-artifact@v4
      with:
        name: om_artifacts
        path: om/*.om
